### PR TITLE
add typescript definitions

### PR DESCRIPTION
**Pull request by neodon**
Pardon my lack of experience with GitHub PRs.

- #7

### CODE REVIEW

**Comment by TimDaub** [comment]
hey sorry I didn't mean to mark your pr ready for review. I wanted to approve it for github actions to be run sorry.

**Comment by neodon** [comment]
That's ok.  I think this is ready as a first pass that adds usable types, pending any questions/concerns you have.

**Comment by TimDaub** [comment]
is it possible that we can add a test that confirms that the type file is passing the Typescript interpreter? I want to avoid releasing it with potential syntax errors

**Comment by neodon** [comment]
That's a good call -- I added a step to CI to compile/check both the JavaScript and the type definitions without writing any extra output files.

**Comment by TimDaub** [comment]
great thanks

**Comment by TimDaub** [comment]
released in 0.0.3

**Pull request merged**
